### ISSUE TITLE
the input datatype of the gene expression matrix in function "calculateSMI"

### ISSUE THREAD

**Issue by LiuCanidk** [sidmall/PDSclassifier#3]
Thanks for your development with this nice package.

I notice that in the user guide, there is no illustration for the input datatype of the function "calculateSMI". From the paper, I learned that the behind algorithm was the same as the ssGSEA, however, there are two input datatypes in the ssGSEA algorithms, that is, raw counts (discontinuous) and log-transformed TPM/RPKM, etc. (continuous). They correspond to different kcdf parameter, Poisson or Gaussian distribution. And I did not notice any parameter that was used to specify the ssGSEA kcdf.

So, could you please specify the input datatypes of the gene expression matrix for the function "calculateSMI"? (I did notice that the data type in the paper was raw RNA count, so I guess it is count, but to be sure about the calculation progress, I raised this issue)

Apologize for any disturbance or offense.

**Comment by sidmall** [comment]
Hi @LiuCanidk,

Thank you for your question.

Yes, you are correct. We have not specified any parameters on `kcdf` for ssGSEA, and we have left it at default within the `gsva()` function of the `GSVA` package. I would recommend you use your normalised data (TPM/RPKM) rather than raw counts to generate SMI with `calculateSMI` directly. However, alternatively, you can also follow up the calculation of SMI detailed in now published https://www.nature.com/articles/s41588-024-01654-5, without having to use the `calculateSMI` if you so desire. All you will require is to use the two gene signatures (MYC targets and PRC targets – can be found within the `PDSclassifier` R package) to generate ssGSEA score, followed by SMI.

Hope this helps.
